- name: 'OS Set up'
  hosts: [ windows ]
  gather_facts: no
  tags: OS

  tasks:
    - name: Add a user
      win_user:
        name: 'ansible'
        password: 'p@ssw0rd'
        groups: 'Users,Remote Desktop Users'
        groups_action: 'add'

    - name: 'Create directory structure'
      win_file:
        path: 'C:\CMT\log\server'
        state: 'directory'

    - name: 'Create directory structure 2'
      win_file:
        path: 'C:\CMT\log\storage'
        state: 'directory'
